# Generated by Django 3.2.3 on 2022-03-14 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_pk', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=512)),
                ('price', models.FloatField()),
                ('catagory', models.CharField(max_length=128)),
                ('sold_status', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-images')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='ProdComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor', to='seller.seller')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentproduct', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='FaveProduct',
            fields=[
                ('p_pk', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('faver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faver', to='seller.seller')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product')),
            ],
        ),
    ]
