# Generated by Django 3.2.3 on 2022-03-14 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodcomment',
            name='id',
        ),
        migrations.AddField(
            model_name='prodcomment',
            name='p_pk',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
