# Generated by Django 3.2.3 on 2022-03-14 20:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('product', '0002_auto_20220314_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('p_pk', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0)),
                ('rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rating', to='product.product')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_rating', to='seller.seller')),
            ],
        ),
    ]
