# Generated by Django 3.2.3 on 2022-05-09 11:20

from django.db import migrations, models
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=seller.models.image_path_generator),
        ),
    ]
